services:
  web:
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'

# Other services will need to be this file
# https://hub.docker.com/_/eclipse-mosquitto
# https://hub.docker.com/r/zerotier/zerotier note: zerotier is the only one that need to be connected to the host network
# https://hub.docker.com/_/mongo
# https://docs.docker.com/compose/how-tos/networking/
# For the zerotier api key, it is recommanded to use a https://docs.docker.com/compose/how-tos/use-secrets/ to store it

