services:
  web:
    build:
      context: app
      target: builder
    container_name: python
    ports:
      - '8000:8000'
    depends_on:
      - mosquitto-broker
    environment:
      BROKER_IP: "mqtt-broker"  # Nom du service Docker pour le broker MQTT
      BROKER_PORT: "1883"       # Port MQTT
      MQTT_TOPIC: "HEPL/M18/test"

      #MONGO_IP: "mongoDB"
      MONGO_PORT: "27017"

  mosquitto-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883" # Port MQTT standard
      - "8883:8883" # Port MQTT sécurisé (SSL/TLS)
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf # Fichier de configuration locale
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

#  mongo:
#    image: mongo:latest
#    container_name: mongoDB
#    ports:
#      - "27017:27017" # Port mongodb par défaut
#    volumes:
#      - mongo-data:/data/db

volumes:
  mosquitto-data:
  mosquitto-log:
#  mongo-data:
